src/main/java/cn/iutils/sys/entity/Config.java
package cn.iutils.sys.entity;

import cn.iutils.sys.entity.DataEntity;

/**
* 公共配置表
* @author iutils.cn
* @version 1.0
*/
public class Config extends DataEntity<Config>{

    private static final long serialVersionUID = 1L;

    private String sysName;//系统名称
    private String moduleName;//模块名称
    private String configName;//配置key
    private String configValue;//配置值

    public Config() {
        super();
    }
    public Config(String id){
        super(id);
    }

    public String getSysName(){
        return sysName;
    }

    public void setSysName(String sysName){
        this.sysName = sysName;
    }

    public String getModuleName(){
        return moduleName;
    }

    public void setModuleName(String moduleName){
        this.moduleName = moduleName;
    }

    public String getConfigName(){
        return configName;
    }

    public void setConfigName(String configName){
        this.configName = configName;
    }

    public String getConfigValue(){
        return configValue;
    }

    public void setConfigValue(String configValue){
        this.configValue = configValue;
    }

}

src/main/java/cn/iutils/sys/entity/DataEntity.java
package cn.iutils.sys.entity;

import cn.iutils.common.BaseEntity;
import cn.iutils.common.utils.UserUtils;

import java.util.Date;

/**
 * 数据实体
 * Created by CC on 16/9/24.
 */
public abstract class DataEntity<T> extends BaseEntity<T> {

    private static final long serialVersionUID = 1L;

    private User user;//当前用户
    private User createUser;//创建人
    private User updateUser;//更新人

    public DataEntity() {
        this.status = STATUS_NORMAL;
    }

    public DataEntity(String id) {
        this();
        this.id = id;
    }


    /**
     * 插入之前执行方法，子类实现
     */
    public void preInsert() {
        User user = UserUtils.getLoginUser();
        if (user != null) {
            this.updateBy = user.getId();
            this.createBy = user.getId();
        }
        this.createDate = new Date();
        this.updateDate = new Date();
    }

    /**
     * 更新之前执行方法，子类实现
     */
    public void preUpdate() {
        User user = UserUtils.getLoginUser();
        if (user != null) {
            this.updateBy = user.getId();
        }
        this.updateDate = new Date();
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public User getCreateUser() {
        return createUser;
    }

    public void setCreateUser(User createUser) {
        this.createUser = createUser;
    }

    public User getUpdateUser() {
        return updateUser;
    }

    public void setUpdateUser(User updateUser) {
        this.updateUser = updateUser;
    }
}

src/main/java/cn/iutils/sys/entity/MsgReceive.java
package cn.iutils.sys.entity;

import cn.iutils.sys.entity.DataEntity;

/**
* 消息接收表
* @author iutils.cn
* @version 1.0
*/
public class MsgReceive extends DataEntity<MsgReceive>{

    private static final long serialVersionUID = 1L;

    private String msgId;//消息编号

    private MsgSend msgSend;//消息主体

    public MsgReceive() {
        super();
    }
    public MsgReceive(String id){
        super(id);
    }

    public String getMsgId(){
        return msgId;
    }

    public void setMsgId(String msgId){
        this.msgId = msgId;
    }

    public MsgSend getMsgSend() {
        return msgSend;
    }

    public void setMsgSend(MsgSend msgSend) {
        this.msgSend = msgSend;
    }
}

src/main/java/cn/iutils/sys/entity/MsgSend.java
package cn.iutils.sys.entity;

import cn.iutils.sys.entity.enums.MsgEnum;

/**
* 消息发送表
* @author iutils.cn
* @version 1.0
*/
public class MsgSend extends DataEntity<MsgSend>{

    private static final long serialVersionUID = 1L;

    private MsgEnum type;//消息类型  系统通知  站内信 用户通知
    private String title;//标题
    private String content;//内容
    private int level;//级别 -1低 0普通 1高
    private String users;//发送给

    public MsgSend() {
        super();
    }
    public MsgSend(String id){
        super(id);
    }

    public MsgEnum getType() {
        return type;
    }

    public void setType(MsgEnum type) {
        this.type = type;
    }

    public String getTitle(){
        return title;
    }

    public void setTitle(String title){
        this.title = title;
    }

    public String getContent(){
        return content;
    }

    public void setContent(String content){
        this.content = content;
    }

    public int getLevel(){
        return level;
    }

    public void setLevel(int level){
        this.level = level;
    }

    public String getUsers() {
        return users;
    }

    public void setUsers(String users) {
        this.users = users;
    }
}

src/main/java/cn/iutils/sys/entity/Organization.java
package cn.iutils.sys.entity;

import cn.iutils.common.BaseEntity;

/**
 * 组织机构表
 * 
 * @author cc
 */
public class Organization extends DataEntity<Organization> {

	private static final long serialVersionUID = 1L;
	private String name; // 组织机构名称
	private String parentId; // 父编号
	private Organization organization;//上级机构
	private String parentIds; // 父编号列表
	private Boolean available = Boolean.TRUE;

	public Organization() {
		super();
	}

	public Organization(String id) {
		super(id);
	}

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getParentId() {
        return parentId;
    }

    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    public String getParentIds() {
        return parentIds;
    }

    public void setParentIds(String parentIds) {
        this.parentIds = parentIds;
    }

	public Organization getOrganization() {
		return organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
	}

	public Boolean getAvailable() {
		return available;
	}

	public void setAvailable(Boolean available) {
		this.available = available;
	}

	public boolean isRootNode() {
		return parentId.equals("0");
	}

}

src/main/java/cn/iutils/sys/entity/Resource.java
package cn.iutils.sys.entity;

import cn.iutils.common.BaseEntity;
import cn.iutils.sys.entity.enums.ResourceEnum;

import java.util.Set;

/**
 * 资源表
 * 
 * @author cc
 */
public class Resource extends DataEntity<Resource> {

	private static final long serialVersionUID = 1L;

	private String name; // 资源名称
	private ResourceEnum type = ResourceEnum.menu; // 资源类型
	private String icon;//图标
	private String url; // 资源路径
	private String permission; // 权限字符串
	private String parentId; // 父编号
	private Resource resource;//上级资源
	private String parentIds; // 父编号列表
	private int sort=0;// 排序
	private Boolean available = Boolean.TRUE;//是否可用

	public Resource() {
		super();
	}

	public Resource(String id) {
		super(id);
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public ResourceEnum getType() {
		return type;
	}

	public void setType(ResourceEnum type) {
		this.type = type;
	}

	public String getIcon() {
		return icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getPermission() {
		return permission;
	}

	public void setPermission(String permission) {
		this.permission = permission;
	}

	public String getParentId() {
		return parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	public String getParentIds() {
		return parentIds;
	}

	public void setParentIds(String parentIds) {
		this.parentIds = parentIds;
	}

	public int getSort() {
		return sort;
	}

	public void setSort(int sort) {
		this.sort = sort;
	}

	public Boolean getAvailable() {
		return available;
	}

	public void setAvailable(Boolean available) {
		this.available = available;
	}

	public boolean isRootNode() {
		return parentId.equals("0");
	}

	public String makeSelfAsParentIds() {
		return getParentIds() + getId() + "/";
	}

	public Resource getResource() {
		return resource;
	}

	public void setResource(Resource resource) {
		this.resource = resource;
	}
}

src/main/java/cn/iutils/sys/entity/ScheduleJob.java
package cn.iutils.sys.entity;

import cn.iutils.common.BaseEntity;

/**
 * 任务调度
 * 
 * @author MyCode
 * @version 1.0
 */
public class ScheduleJob extends DataEntity<ScheduleJob> {

	private static final long serialVersionUID = 1L;

	private String jobName;// 任务名称
	private String jobGroup;// 任务分组
	private String cron;// cron表达式
	private String beanClass;// 任务执行时调用哪个类的方法 包名+类名
	private String isConcurrent;// 是否有状态
	private String methodName = "run";// 任务调用的方法名

	public static final String STATUS_RUNNING = "1";
	public static final String STATUS_NOT_RUNNING = "0";
	public static final String CONCURRENT_IS = "1";
	public static final String CONCURRENT_NOT = "0";

	public ScheduleJob() {
		super();
	}

	public ScheduleJob(String id) {
		super(id);
	}

	public String getJobName() {
		return jobName;
	}

	public void setJobName(String jobName) {
		this.jobName = jobName;
	}

	public String getJobGroup() {
		return jobGroup;
	}

	public void setJobGroup(String jobGroup) {
		this.jobGroup = jobGroup;
	}

	public String getCron() {
		return cron;
	}

	public void setCron(String cron) {
		this.cron = cron;
	}

	public String getBeanClass() {
		return beanClass;
	}

	public void setBeanClass(String beanClass) {
		this.beanClass = beanClass;
	}

	public String getIsConcurrent() {
		return isConcurrent;
	}

	public void setIsConcurrent(String isConcurrent) {
		this.isConcurrent = isConcurrent;
	}

	public String getMethodName() {
		return methodName;
	}

	public void setMethodName(String methodName) {
		this.methodName = methodName;
	}

}

src/main/java/cn/iutils/sys/entity/enums/DataScopeEnum.java
package cn.iutils.sys.entity.enums;

/**
 * 数据范围
 * @author cc
 */
public enum DataScopeEnum {

	all("所有数据"),orgFollow("所在机构及以下数据"), org("所在机构数据"),self("仅本人数据");

	private final String info;

	private DataScopeEnum(String info) {
		this.info = info;
	}

	public String getInfo() {
		return info;
	}

}

src/main/java/cn/iutils/sys/controller/ConfigController.java
package cn.iutils.sys.controller;

import cn.iutils.common.BaseController;
import cn.iutils.common.Page;
import cn.iutils.common.utils.CacheUtils;
import cn.iutils.common.utils.JStringUtils;
import cn.iutils.sys.entity.Config;
import cn.iutils.sys.service.ConfigService;
import org.apache.shiro.authz.annotation.RequiresPermissions;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

/**
* 公共配置表 控制器
* @author iutils.cn
* @version 1.0
*/
@Controller
@RequestMapping("${adminPath}/sys/config")
public class ConfigController extends BaseController {

    @Autowired
    private ConfigService configService;

    @ModelAttribute
    public Config get(@RequestParam(required = false) String id) {
        Config entity = null;
        if (JStringUtils.isNotBlank(id)) {
            entity = configService.get(id);
        }
        if (entity == null) {
            entity = new Config();
        }
        return entity;
    }

    @RequiresPermissions("sys:config:view")
    @RequestMapping()
    public String list(Config config,Model model, Page<Config> page) {
        page.setEntity(config);
        model.addAttribute("page", page.setList(configService.findPage(page)));
        return "sys/config/list";
    }

    @RequiresPermissions("sys:config:create")
    @RequestMapping(value = "/create", method = RequestMethod.GET)
    public String create(Config config,Model model) {
        model.addAttribute("config", config);
        return "sys/config/form";
    }

    @RequiresPermissions("sys:config:create")
    @RequestMapping(value = "/create", method = RequestMethod.POST)
    public String create(Config config, RedirectAttributes redirectAttributes) {
        configService.save(config);
        addMessage(redirectAttributes,"新增成功");
        return "redirect:"+ adminPath +"/sys/config/update?id="+config.getId();
    }

    @RequiresPermissions("sys:config:update")
    @RequestMapping(value = "/update", method = RequestMethod.GET)
    public String update(Config config, Model model) {
        model.addAttribute("config", config);
        return "sys/config/form";
    }

    @RequiresPermissions("sys:config:update")
    @RequestMapping(value = "/update", method = RequestMethod.POST)
    public String update(Config config, RedirectAttributes redirectAttributes) {
        configService.save(config);
        CacheUtils.remove(config.getSysName() + config.getModuleName() + config.getConfigName());
        addMessage(redirectAttributes,"修改成功");
        return "redirect:"+ adminPath +"/sys/config/update?id="+config.getId();
    }

    @RequiresPermissions("sys:config:delete")
    @RequestMapping(value = "/{id}/delete", method = RequestMethod.GET)
    public String delete(@PathVariable("id") String id,int pageNo,int pageSize, RedirectAttributes redirectAttributes) {
        Config config = configService.get(id);
        configService.delete(config);
        CacheUtils.remove(config.getSysName() + config.getModuleName() + config.getConfigName());
        addMessage(redirectAttributes,"删除成功");
        return "redirect:"+ adminPath +"/sys/config?pageNo="+pageNo+"&pageSize="+pageSize;
    }
}

src/main/java/cn/iutils/sys/controller/IndexController.java
package cn.iutils.sys.controller;

import java.util.List;
import java.util.Set;

import cn.iutils.common.utils.SystemUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import cn.iutils.common.BaseController;
import cn.iutils.sys.entity.Resource;
import cn.iutils.sys.service.ResourceService;
import cn.iutils.sys.service.UserService;

/**
 * 首页控制器
 * 
 * @author cc
 */
@Controller
@RequestMapping(value = "${adminPath}")
public class IndexController extends BaseController {

	@Autowired
	private ResourceService resourceService;

	@Autowired
	private UserService userService;

	@RequestMapping(method = RequestMethod.GET)
	public String index(Model model) {
		Set<String> permissions = userService.findPermissions();
		List<Resource> menus = resourceService.findMenus(permissions);
		model.addAttribute("menus", menus);
		return "index";
	}

	@RequestMapping(value = "/welcome", method = RequestMethod.GET)
	public String welcome(Model model) {
		model.addAttribute("systemInfo", SystemUtils.getSystemInfo());
		return "welcome";
	}

}

src/main/java/cn/iutils/sys/controller/LogController.java
package cn.iutils.sys.controller;

import cn.iutils.common.BaseController;
import cn.iutils.common.Page;
import cn.iutils.common.utils.JStringUtils;
import cn.iutils.sys.entity.SLog;
import cn.iutils.sys.service.SLogService;
import org.apache.shiro.authz.annotation.RequiresPermissions;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

/**
 * 日志记录 控制器
 *
 * @author iutils
 * @version 1.0
 */
@Controller
@RequestMapping("${adminPath}/slog")
public class LogController extends BaseController {

    @Autowired
    private SLogService logService;

    @ModelAttribute
    public SLog get(@RequestParam(required = false) String id) {
        SLog entity = null;
        if (JStringUtils.isNotBlank(id)) {
            entity = logService.get(id);
        }
        if (entity == null) {
            entity = new SLog();
        }
        return entity;
    }

    /**
     * 查看日志列表
     *
     * @param model
     * @param page
     * @return
     */
    @RequiresPermissions("sys:slog:view")
    @RequestMapping()
    public String list(SLog sLog, Model model, Page<SLog> page) {
        page.setEntity(sLog);
        if(JStringUtils.isBlank(sLog.getOrderBy())){
            page.setOrderBy("a.create_date desc");
        }else{
            page.setOrderBy(sLog.getOrderBy());
        }
//        //切换数据源
//        DataSourceContextHolder.setDbType(DataSourceType.dataSource_2);
        model.addAttribute("page", page.setList(logService.findPage(page)));
//        //清除数据源 使用默认数据源
//        DataSourceContextHolder.clearDbType();
        return "sys/log/list";
    }

    /**
     * 查看日志详细
     *
     * @param log
     * @param model
     * @return
     */
    @RequiresPermissions("sys:slog:view")
    @RequestMapping(value = "/update", method = RequestMethod.GET)
    public String update(SLog log, Model model) {
        model.addAttribute("log", log);
        return "sys/log/edit";
    }

    /**
     * 批量删除日志
     *
     * @param ids
     * @param redirectAttributes
     * @return
     */
    @RequiresPermissions("sys:slog:edit")
    @RequestMapping(value = "/delete", method = RequestMethod.GET)
    public String delete(String[] ids, int pageNo, int pageSize,
                         RedirectAttributes redirectAttributes) {
        logService.deleteAll(ids);
        addMessage(redirectAttributes, "删除成功");
        return "redirect:" + adminPath + "/slog?pageNo=" + pageNo + "&pageSize=" + pageSize;
    }

}

src/main/webapp/WEB-INF/view/sys/resource/add.jsp
<%@ page contentType="text/html;charset=UTF-8" %>
<%@ include file="/WEB-INF/view/include/taglib.jsp"%>
<html>
<head>
	<title>资源编辑</title>
	<%@ include file="../../include/head.jsp"%>
	<style type="text/css">
		.tpl-content-wrapper{margin-left:0}
	</style>
</head>
<body>
<script src="${ctxStatic}/assets/js/theme.js"></script>
<div class="am-g tpl-g">
	<!-- 内容区域 -->
	<div class="tpl-content-wrapper">
		<div class="row-content am-cf">
			<div class="row">
				<div class="am-u-sm-12 am-u-md-12 am-u-lg-12">
					<div class="widget am-cf">
						<div class="widget-head am-cf">
							<div class="widget-title am-fl">资源新增</div>
						</div>
						<div class="widget-body am-fr">
							<form class="am-form tpl-form-border-form" data-am-validator modelAttribute="resource" action="${ctx}/resource/update" method="post">
								<input type="hidden" name="parentId" value="${resource.id}" />
								<input type="hidden" name="parentIds" value="${resource.parentIds}${resource.id}/" />
								<div class="am-form-group">
									<label class="am-u-sm-3 am-form-label">上级资源：</label>
									<div class="am-u-sm-9">
										<input type="text" id="parentName" minlength="1" value="${resource.name}" readonly/>
									</div>
								</div>
								<div class="am-form-group">
									<label class="am-u-sm-3 am-form-label"><span class="error">*</span>资源名称：</label>
									<div class="am-u-sm-9">
										<input type="text" name="name" minlength="1" placeholder="资源名称（必填）" required />
									</div>
								</div>
								<div class="am-form-group">
									<label class="am-u-sm-3 am-form-label"><span class="error">*</span>排序：</label>
									<div class="am-u-sm-9">
										<input type="number" name="sort" minlength="1" value="0" placeholder="排序（必填）" required />
									</div>
								</div>
								<div class="am-form-group">
									<label class="am-u-sm-3 am-form-label">类型：</label>
									<div class="am-u-sm-9">
										<select name="type" data="menu">
											<c:forEach items="${types}" var="m">
												<option value="${m}">${m.info}</option>
											</c:forEach>
										</select>
									</div>
								</div>
								<div class="am-form-group">
									<label class="am-u-sm-3 am-form-label">图标：</label>
									<div class="am-u-sm-9">
										<div class="am-input-group">
											<input type="text" id="icon" name="icon" class="am-form-field" placeholder="图标"
												   value="${resource.icon}" />
							      <span class="am-input-group-btn">
							      	<input type="file" name="file" id="file" style="display: none;" />
							        <button class="am-btn am-btn-default" id="btnPicture" type="button">上传图标</button>
							      </span>
										</div>
									</div>
								</div>
								<div class="am-form-group">
									<label class="am-u-sm-3 am-form-label">URL路径：</label>
									<div class="am-u-sm-9">
										<input type="text" name="url" />
									</div>
								</div>
								<div class="am-form-group">
									<label class="am-u-sm-3 am-form-label">权限字符串：</label>
									<div class="am-u-sm-9">
										<input type="text" name="permission" />
									</div>
								</div>
								<div class="am-form-group">
									<label class="am-u-sm-3 am-form-label">是否可用：</label>
									<div class="am-u-sm-9">
										<select name="available" data="true">
											<option value="true">可用</option>
											<option value="false">禁用</option>
										</select>
									</div>
								</div>
								<div class="am-form-group">
									<div class="am-u-sm-9 am-u-sm-push-3">
										<shiro:hasPermission name="sys:organization:edit"><button type="submit" class="am-btn am-btn-primary">保存</button></shiro:hasPermission>
										<button type="button" class="am-btn am-btn-danger" onclick="closeModel(false)">关闭</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<%@ include file="../../include/bottom.jsp"%>
<script type="text/javascript" src="${ctxStatic}/custom/js/ajaxfileupload.js"></script>
<script type="text/javascript">
	$(function () {
		//消息提醒
		var msg = '${msg}';
		if(msg!=''){
			showMsg(msg);
			closeModel(true);//关闭窗口
		}
		initSelectValue(true);//初始化下拉框的值
	});
	$(document).ready(function() {
		//触发选择文件
		$("#btnPicture").click(function(){
			$("#file").click();
		});
		//选择文件后
		$("#file").change(function(){
			$.ajaxFileUpload({
				url: '${ctx}/upload/local',
				type: 'post',
				secureuri: false,
				fileElementId: 'file',
				dataType: 'text',
				success: function (data, status)
				{
					data = JSON.parse(delHtmlTag(data));
					if(data.ret==1){
						$("#icon").val(data.data);
					}else{
						alert(data.msg);
					}
				},
				error: function (data, status, e)
				{
					alert(e);
				}
			});
		});
	});
</script>
</body>
</html>

src/main/webapp/WEB-INF/view/sys/resource/list.jsp
<%@ page contentType="text/html;charset=UTF-8"%>
<%@ include file="/WEB-INF/view/include/taglib.jsp"%>
<html>
<head>
	<title>资源管理列表</title>
	<%@ include file="../../include/head.jsp"%>
	<link rel="stylesheet" href="${ctxStatic}/3rd-lib/jquery-ztree/css/zTreeStyle.css">
	<style type="text/css">
		.tpl-content-wrapper{margin-left:0}
	</style>
</head>
<body>
<script src="${ctxStatic}/assets/js/theme.js"></script>
<div class="am-g tpl-g">
	<!-- 内容区域 -->
	<div class="tpl-content-wrapper">
		<div class="row-content am-cf">
			<div class="row">
				<div class="am-u-sm-12 am-u-md-12 am-u-lg-3">
					<div class="widget am-cf">
						<div class="widget-head am-cf">
							<div class="widget-title am-fl">资源树</div>
						</div>
						<div class="widget-body widget-body-lg am-fr">
							<div class="am-scrollable-horizontal">
								<ul id="tree" class="ztree"></ul><!-- 资源树 -->
							</div>
						</div>
					</div>
				</div>

				<div class="am-u-sm-12 am-u-md-12 am-u-lg-9">
					<div class="widget am-cf">
						<div class="widget-head am-cf">
							<div class="widget-title am-fl">资源列表</div>
						</div>
						<div class="widget-body am-fr">
							<div class="am-u-sm-12 am-u-md-3 am-u-lg-3">
								<div class="am-btn-toolbar">
									<div class="am-btn-group am-btn-group-xs">
										<shiro:hasPermission name="sys:resource:edit">
											<button type="button" class="am-btn am-btn-default am-btn-success"
													onclick="openModel(false,'${ctx}/resource/create?id=${page.entity.id}')"><span class="am-icon-plus"></span> 新增
											</button></shiro:hasPermission>
									</div>
								</div>
							</div>

							<div class="am-u-sm-12 am-u-md-9 am-u-lg-9">
								<form id="searchForm" action="${ctx}/resource" method="post" style="display: none;">
									<input name="id" value="${page.entity.id}" />
									<input id="pageNo" name="pageNo" type="hidden" value="${page.pageNo}"/>
									<input id="pageSize" name="pageSize" type="hidden" value="${page.pageSize}"/>
									<div class="am-input-group am-input-group-sm tpl-form-border-form cl-p">

									</div>
								</form>
							</div>

							<div class="am-u-sm-12">
								<table id="contentTable" class="am-table am-table-compact am-table-striped tpl-table-black">
									<thead>
									<tr>
										<th>编号</th>
										<th>归属资源</th>
										<th>资源名称</th>
										<th>资源类型</th>
										<th>链接</th>
										<th>排序</th>
										<th>是否可用</th>
										<th>权限标识</th>
										<shiro:hasPermission name="sys:resource:edit"><th>操作</th></shiro:hasPermission>
									</tr>
									</thead>
									<tbody>
									<c:forEach items="${page.list}" var="resource" varStatus="status">
										<tr>
											<td>${status.index+1}</td>
											<td>${resource.resource.name}</td>
											<td>${resource.name}</td>
											<td><span class="am-badge am-badge-primary am-radius">${resource.type.info}</span></td>
											<td>${resource.url}</td>
											<td>${resource.sort}</td>
											<td>${resource.available?'<span class="am-badge am-badge-success am-radius">可用</span>':'<span class="am-badge am-badge-danger am-radius">禁用</span>'}</td>
											<td>${resource.permission}</td>
											<shiro:hasPermission name="sys:resource:edit"><td>
												<a href="javascript:;" onclick="openModel(false,'${ctx}/resource/update?id=${resource.id}')" title="编辑"><span class="am-icon-pencil"></span></a>
												<a href="${ctx}/resource/delete?id=${resource.id}&pageNo=${page.pageNo}&pageSize=${page.pageSize}"
												   onclick="return confirm('确认要删除该条数据吗？', this.href)" title="删除"><span class="am-text-danger am-icon-trash-o"></span></a></td></shiro:hasPermission>
										</tr>
										</tr>
									</c:forEach>
									</tbody>
								</table>
							</div>

							<div class="am-u-lg-12 am-cf">
								<%@ include file="../../utils/pagination.jsp" %>
							</div>

						</div>
					</div>
				</div>

			</div>
		</div>
	</div>
</div>
<%@ include file="../../include/bottom.jsp"%>
<script src="${ctxStatic}/3rd-lib/jquery-ztree/js/jquery.ztree.core-3.5.min.js"></script>
<script>
	$(function () {
		var setting = {
			data: {
				simpleData: {
					enable: true
				}
			},
			callback : {
				onClick : function(event, treeId, treeNode) {
					location.href = "${ctx}/resource?id="+treeNode.id;
				}
			}
		};
		var zNodes =[
			<c:forEach items="${resourceList}" var="o" varStatus="status">
			{ id:${o.id}, pId:${o.parentId}, name:"${o.name}", open:${o.rootNode}}<c:if test="${!status.last}">,</c:if>
			</c:forEach>
		];
		$(document).ready(function(){
			var ztree = $.fn.zTree.init($("#tree"), setting, zNodes);
			ztree.expandAll(true);
		});
	});
</script>
<script>
	$(document).ready(function () {
		var msg = '${msg}';
		if(msg!=''){
			showMsg(msg);
		}
	});
</script>
</body>
</html>